sudo: required
services:
  - docker

before_install:
  - docker build -t parkyes90/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true parkyes90/react-test npm test -- --coverage

after_success:
  - docker build -t parkyes90/multi-client ./client
  - docker build -t parkyes90/multi-nginx ./nginx
  - docker build -t parkyes90/multi-server ./server
  - docker build -t parkyes90/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push parkyes90/multi-client
  - docker push parkyes90/multi-nginx
  - docker push parkyes90/multi-server
  - docker push parkyes90/multi-worker